stages:
  - test
  - deploy
      
# if pytest succeeds or no tests are run, continue to deploy
pytest:
  stage: test
  script:
    - python3 -m pytest tests ; ret=$? ; [ $ret -eq 0 ] || [ $ret -eq 5 ] 

Conda Release:
  only:
    - tags
  stage: deploy
  variables:
    CAD_CHANNEL: /home/cfsa/sclark/Documents/git_ci_tests/conda_repo/
  environment:
    name: Conda
  script:
    - mkdir dist
    - conda-build --output-folder $CAD_CHANNEL .

Filesystem Release:
  only:
    - tags
  stage: deploy
  variables:
    RELEASE_DIR: /ride/release/python/lib/
  environment:
    name: Filesystem
  script:
    - python3 setup.py install --root $RELEASE_DIR