stages:
  - test
  - deploy
      

variables:
  PYTHON_VERSION: python3

before_script:
  - source ~gitlab-runner/.bashrc
  - virtualenv --python $PYTHON_VERSION --system-site-packages venv
  - source venv/bin/activate

cache: 
  paths:
    - .cache/pip
    - venv/

# if pytest succeeds or no tests are run, continue to deploy
.pytest:
  only:
    - tags
  stage: test
  script:
    - >
      if [ ! -s requirements.txt ] && python3 -m pytest --co; then
        pip install -r requirements.txt
        python3 -m pytest tests ; ret=$? ; [ $ret -eq 0 ] || [ $ret -eq 5 ] 
      fi

release:
  only:
    - tags
  stage: deploy
  variables:
    PACKAGE_NAME: multinet
    REL_ROOT: /ride/release/python/packages
  environment:
    name: release
  script:
    - ./setup.py sdist --dist-dir $REL_ROOT